# Generated by Django 5.0.7 on 2024-07-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('featured_image', models.ImageField(upload_to='images/')),
                ('link', models.URLField()),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
