# Generated by Django 5.0.7 on 2024-08-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="featured_image",
        ),
        migrations.AddField(
            model_name="entry",
            name="featured_image_url",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
