# Generated by Django 4.2.3 on 2024-08-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_entry_featured_image_entry_featured_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='link',
            field=models.URLField(max_length=300),
        ),
    ]
