version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # React app will be available on port 3000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app # Map your backend folder to the app directory in the container
    ports:
      - "8000:8000" # Django app will be available on port 8000
    depends_on:
      - frontend
